apiVersion: v1
kind: Service
metadata:
  name: cpp-server2
spec:
  type: NodePort  # Sử dụng NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002  # Bạn có thể chỉ định port để dễ dàng kết nối
  selector:
    app: server2

    # kubectl apply -f service.yaml
